-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 21:39:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Decay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Decay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Decay` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `Decay` ;

-- -----------------------------------------------------
-- Table `Decay`.`Detectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`Detectors` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`ImportedFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`ImportedFiles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DetectorID` INT NULL,
  `FilePath` VARCHAR(255) NULL,
  `FileName` VARCHAR(255) NULL,
  `ImportDate` DATETIME NULL,
  `ConvertDate` DATETIME NULL,
  `ConvertedBy` VARCHAR(255) NULL,
  `DataType` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `importedfile_detector_fk_idx` (`DetectorID` ASC) VISIBLE,
  CONSTRAINT `importedfile_detector_fk`
    FOREIGN KEY (`DetectorID`)
    REFERENCES `Decay`.`Detectors` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`QC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`QC` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DetectorID` INT NULL,
  `FileID` INT NULL,
  `AcquisitionStartTime` DATETIME NULL,
  `Realtime` DOUBLE NULL,
  `AcquisitionLength` DOUBLE NULL,
  `CalibrationDate` DATETIME NULL,
  `Valid` TINYINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `qc_detector_fk_idx` (`DetectorID` ASC) VISIBLE,
  INDEX `qc_importedfile_fk_idx` (`FileID` ASC) VISIBLE,
  CONSTRAINT `qc_detector_fk`
    FOREIGN KEY (`DetectorID`)
    REFERENCES `Decay`.`Detectors` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `qc_importedfile_fk`
    FOREIGN KEY (`FileID`)
    REFERENCES `Decay`.`ImportedFiles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`QCEnergy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`QCEnergy` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QCID` INT NULL,
  `X` DOUBLE NULL,
  `Y` DOUBLE NULL,
  `Error` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `qcenergy_qc_idx` (`QCID` ASC) VISIBLE,
  CONSTRAINT `qcenergy_qc`
    FOREIGN KEY (`QCID`)
    REFERENCES `Decay`.`QC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`QCEfficiency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`QCEfficiency` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QCID` INT NULL,
  `X` DOUBLE NULL,
  `Y` DOUBLE NULL,
  `Error` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `qcefficiency_qc_fk_idx` (`QCID` ASC) VISIBLE,
  CONSTRAINT `qcefficiency_qc_fk`
    FOREIGN KEY (`QCID`)
    REFERENCES `Decay`.`QC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`QCSpectrum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`QCSpectrum` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QCID` INT NULL,
  `X` DOUBLE NULL,
  `Y` DOUBLE NULL,
  `Error` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `qcspectrum_qc_fk_idx` (`QCID` ASC) VISIBLE,
  CONSTRAINT `qcspectrum_qc_fk`
    FOREIGN KEY (`QCID`)
    REFERENCES `Decay`.`QC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`QCCertificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`QCCertificate` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QCID` INT NULL,
  `AbsoluteActivity` INT NULL,
  `DateTime` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `qccertificate_qc_fk_idx` (`QCID` ASC) VISIBLE,
  CONSTRAINT `qccertificate_qc_fk`
    FOREIGN KEY (`QCID`)
    REFERENCES `Decay`.`QC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`SOH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`SOH` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DetectorID` INT NULL,
  `FileID` INT NULL,
  `RoomTemperature` FLOAT NULL,
  `ShieldStatus` TINYINT NULL,
  `Humidity` INT NULL,
  `HighVoltage` INT NULL,
  `CrystalTemperature` INT NULL,
  `DateTime` DATETIME NULL,
  `MeasurementTime` INT NULL,
  `Valid` TINYINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `soh_detectors_fk_idx` (`DetectorID` ASC) VISIBLE,
  INDEX `soh_importedfile_fk_idx` (`FileID` ASC) VISIBLE,
  CONSTRAINT `soh_detectors_fk`
    FOREIGN KEY (`DetectorID`)
    REFERENCES `Decay`.`Detectors` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `soh_importedfile_fk`
    FOREIGN KEY (`FileID`)
    REFERENCES `Decay`.`ImportedFiles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`Isotopes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`Isotopes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `HalfLife` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`Intensity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`Intensity` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CertificateID` INT NULL,
  `IsotopeID` INT NULL,
  `RelativeActivity` DOUBLE NULL,
  `Energy` DOUBLE NULL,
  `EnergyPercentage` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `intensity_isotopes_fk_idx` (`IsotopeID` ASC) VISIBLE,
  INDEX `intensity_qccertificate_fk_idx` (`CertificateID` ASC) VISIBLE,
  CONSTRAINT `intensity_isotopes_fk`
    FOREIGN KEY (`IsotopeID`)
    REFERENCES `Decay`.`Isotopes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `intensity_qccertificate_fk`
    FOREIGN KEY (`CertificateID`)
    REFERENCES `Decay`.`QCCertificate` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`Version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`Version` (
  `ID` INT NOT NULL DEFAULT 1,
  `Major` INT NULL,
  `Minor` INT NULL,
  `Revision` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Decay`.`Changes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Decay`.`Changes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UpdateDate` TIMESTAMP NULL,
  `RolloutDate` TIMESTAMP NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
